# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_back_ground = QtWidgets.QLabel(self.centralwidget)
        self.label_back_ground.setGeometry(QtCore.QRect(0, 0, 640, 400))
        self.label_back_ground.setText("")
        self.label_back_ground.setObjectName("label_back_ground")
        self.label_trigger_sensor_name = QtWidgets.QLabel(self.centralwidget)
        self.label_trigger_sensor_name.setGeometry(QtCore.QRect(50, 120, 130, 51))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.label_trigger_sensor_name.setFont(font)
        self.label_trigger_sensor_name.setText("")
        self.label_trigger_sensor_name.setObjectName("label_trigger_sensor_name")
        self.label_project_name = QtWidgets.QLabel(self.centralwidget)
        self.label_project_name.setGeometry(QtCore.QRect(200, 30, 221, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label_project_name.setFont(font)
        self.label_project_name.setText("")
        self.label_project_name.setObjectName("label_project_name")
        self.label_respond_img = QtWidgets.QLabel(self.centralwidget)
        self.label_respond_img.setGeometry(QtCore.QRect(200, 210, 100, 100))
        self.label_respond_img.setText("")
        self.label_respond_img.setObjectName("label_respond_img")
        self.label_trigger_sensor_value = QtWidgets.QLabel(self.centralwidget)
        self.label_trigger_sensor_value.setGeometry(QtCore.QRect(200, 120, 100, 50))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.label_trigger_sensor_value.setFont(font)
        self.label_trigger_sensor_value.setText("")
        self.label_trigger_sensor_value.setObjectName("label_trigger_sensor_value")
        self.label_respond_sensor_name = QtWidgets.QLabel(self.centralwidget)
        self.label_respond_sensor_name.setGeometry(QtCore.QRect(50, 230, 130, 51))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.label_respond_sensor_name.setFont(font)
        self.label_respond_sensor_name.setText("")
        self.label_respond_sensor_name.setObjectName("label_respond_sensor_name")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
